### PR TITLE
Added black-list and size select

### PR DESCRIPTION
**Pull request by s0snooley**
Added black-list and size select
Sorry for the ugly code... :)

### CODE REVIEW

**Comment by RobJDavey** [comment]
I like the idea of adding a blacklist to the extension and I will look at merging this and updating the extension some time soon (probably tomorrow).

However I'm not keen on adding in the size option. Currently the emoji is set to be at 1em, which means it will match the height of the text it's inside. This makes it look the same as it would do if browsed on a Mac OS X or iOS device. If there is a specific situation you are aware of where the emoji is not displaying at the size it should do, then please let me know and I'll investigate what CSS is required to fix this, but for me the idea of fixed image sizes is a no.

**Comment by s0snooley** [comment]
Ok, Thanks for a great extension! :smile:

**Comment by RobJDavey** [comment]
I have reopened this as I have not yet had chance to review / merge the pull request.

**Comment by RobJDavey** [comment]
The blacklist has now been added in 9d4424e so this can now be closed.
I will update the extension after I have had a user test my fix for #23 so I can put 2 fixes in at once.

As for the emoji sizing, I am considering adding a multiplier (e.g. 1.0 is current size, 2.0 will be double).
I will think about this over the next few days and decide over the weekend.

**Pull request closed without merging**
